cd /network_space/server126/shared/sunyx/models/TMR

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_nomask_choreo_aist_maintable/eval/pkl/ep000090 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_nomask_choreo_aist_maintable/eval/pkl/ep000090/motion_guofeats
python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_nomask_choreo_aist_maintable/eval/pkl/ep000090/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/data/choreo/aist/maintable/text --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/ablation_nomask_choreo_aist_maintable_fit.log 2>&1 &

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_part_only_choreo_aist_maintable/eval/pkl/ep000090 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_part_only_choreo_aist_maintable/eval/pkl/ep000090/motion_guofeats
python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_part_only_choreo_aist_maintable/eval/pkl/ep000090/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/data/choreo/aist/maintable/text --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/ablation_part_only_choreo_aist_maintable_fit.log 2>&1 &

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_time_only_choreo_aist_maintable/eval/pkl/ep000075 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_time_only_choreo_aist_maintable/eval/pkl/ep000075/motion_guofeats
python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_time_only_choreo_aist_maintable/eval/pkl/ep000075/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/data/choreo/aist/maintable/text --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/ablation_time_only_choreo_aist_maintable_fit.log 2>&1 &

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_choreo_aist_maintable/eval/pkl/ep000105 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_choreo_aist_maintable/eval/pkl/ep000105/motion_guofeats
python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_choreo_aist_maintable/eval/pkl/ep000105/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/data/choreo/aist/maintable/text --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_fix_choreo_aist_maintable_fit.log 2>&1 &

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_choreo_aist_maintable/eval/pkl/ep000120 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_choreo_aist_maintable/eval/pkl/ep000120/motion_guofeats
python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_choreo_aist_maintable/eval/pkl/ep000120/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/data/choreo/aist/maintable/text --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_fix_attnback_choreo_aist_maintable_fit.log 2>&1 &

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_simpletag_choreo_aist_maintable/eval/pkl/ep000060 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_simpletag_choreo_aist_maintable/eval/pkl/ep000060/motion_guofeats
python aist_recall_finetune_simpletag.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_simpletag_choreo_aist_maintable/eval/pkl/ep000060/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/data/choreo/aist/maintable/text --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_fix_attnback_simpletag_choreo_aist_maintable_fit.log 2>&1 &

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_simpletag_choreo_aist_maintable/eval/pkl/ep000150 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_simpletag_choreo_aist_maintable/eval/pkl/ep000150/motion_guofeats
python aist_recall_finetune_simpletag.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_simpletag_choreo_aist_maintable/eval/pkl/ep000150/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/data/choreo/aist/maintable/text --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_fix_simpletag_choreo_aist_maintable_fit.log 2>&1 &
