cd /network_space/server126/shared/sunyx/models/TMR

# python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_nomask/vis/pkl/ep000090 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_nomask/vis/pkl/ep000090/motion_guofeats
# python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_nomask/vis/pkl/ep000090/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/TMR/recall_info/segment --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/ablation_nomask_gttext_fit.log 2>&1 &

# python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_part_only/vis/pkl/ep000090 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_part_only/vis/pkl/ep000090/motion_guofeats
# python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_part_only/vis/pkl/ep000090/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/TMR/recall_info/segment --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/ablation_part_only_gttext_fit.log 2>&1 &

# python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_time_only/vis/pkl/ep000075 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_time_only/vis/pkl/ep000075/motion_guofeats
# python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/ablation_time_only/vis/pkl/ep000075/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/TMR/recall_info/segment --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/ablation_time_only_gttext_fit.log 2>&1 &

# python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix/vis/pkl/ep000105 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix/vis/pkl/ep000105/motion_guofeats
# python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix/vis/pkl/ep000105/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/TMR/recall_info/segment --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_gttext_fit.log 2>&1 &

# python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback/vis/pkl/ep000120 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback/vis/pkl/ep000120/motion_guofeats
# python aist_recall_finetune.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback/vis/pkl/ep000120/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/TMR/recall_info/segment --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_fix_attnback_gttext_fit.log 2>&1 &

# python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_simpletag/vis/pkl/ep000060 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_simpletag/vis/pkl/ep000060/motion_guofeats
# python aist_recall_finetune_simpletag.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_attnback_simpletag/vis/pkl/ep000060/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/TMR/recall_info/segment --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_fix_attnback_simpletag_gttext_fit.log 2>&1 &

python -m prepare.custom_compute_guoh3dfeats --downsample 60_20 --input_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_simpletag/vis/pkl/ep000150 --output_folder /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_simpletag/vis/pkl/ep000150/motion_guofeats
python aist_recall_finetune_simpletag.py --npy_dir /network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/experiments/cc_motion_gpt_text_fix_simpletag/vis/pkl/ep000150/motion_guofeats --info_dir /network_space/server126/shared/sunyx/models/TMR/recall_info/segment --run_dir /network_space/server126/shared/sunyx/models/TMR/models/tmr_humanml3d_guoh3dfeats >/network_space/server126/shared/sunyx/models/Danceba-spatiotemporal-text/cc_motion_gpt_text_fix_simpletag_gttext_fit.log 2>&1 &
